#include "../include/character_types.h"
#include "../include/affinity.h"

AffinityRules AFFINITYRULES[] = {
    {CLASS_TYPE_DEATH_K, CLASS_TYPE_PYRO, 0.90f},
    {CLASS_TYPE_DEATH_K, CLASS_TYPE_FROST_W, 1.15f},
    {CLASS_TYPE_DEATH_K, CLASS_TYPE_DRUID, 1.15f},
    {CLASS_TYPE_DEATH_K, CLASS_TYPE_COLOSSUS, 0.75f},
    {CLASS_TYPE_DEATH_K, CLASS_TYPE_MURDEROUS, 0.85f},

    {CLASS_TYPE_SHADOW_S, CLASS_TYPE_FROST_W, 1.15f},
    {CLASS_TYPE_SHADOW_S, CLASS_TYPE_PYRO, 0.90f},
    {CLASS_TYPE_SHADOW_S, CLASS_TYPE_DRUID, 0.85f},

    {CLASS_TYPE_PYRO, CLASS_TYPE_FROST_W, 1.25f},
    {CLASS_TYPE_PYRO, CLASS_TYPE_DRUID, 1.5f},
    {CLASS_TYPE_PYRO, CLASS_TYPE_SHADOW_S, 1.15f},
    {CLASS_TYPE_PYRO, CLASS_TYPE_DEATH_K, 1.20f},
    {CLASS_TYPE_PYRO, CLASS_TYPE_MURDEROUS, 0.8f},

    {CLASS_TYPE_FROST_W, CLASS_TYPE_COLOSSUS, 1.4f},
    {CLASS_TYPE_FROST_W, CLASS_TYPE_MURDEROUS, 1.25f},
    {CLASS_TYPE_FROST_W, CLASS_TYPE_PYRO, 1.25f},
    {CLASS_TYPE_FROST_W, CLASS_TYPE_SHADOW_S, 0.85f},
    {CLASS_TYPE_FROST_W, CLASS_TYPE_DEATH_K, 0.85f},
   
    {CLASS_TYPE_MURDEROUS, CLASS_TYPE_DEATH_K, 1.15f},
    {CLASS_TYPE_MURDEROUS, CLASS_TYPE_DRUID, 1.20f},
    {CLASS_TYPE_MURDEROUS, CLASS_TYPE_FROST_W, 0.75f},
    {CLASS_TYPE_MURDEROUS, CLASS_TYPE_COLOSSUS, 0.85f},

    {CLASS_TYPE_COLOSSUS, CLASS_TYPE_DEATH_K, 1.25f},
    {CLASS_TYPE_COLOSSUS, CLASS_TYPE_MURDEROUS, 1.15f},
    {CLASS_TYPE_COLOSSUS, CLASS_TYPE_FROST_W, 0.65f},
    {CLASS_TYPE_COLOSSUS, CLASS_TYPE_DRUID, 0.85f},

    {CLASS_TYPE_DRUID, CLASS_TYPE_SHADOW_S, 1.15f},
    {CLASS_TYPE_DRUID, CLASS_TYPE_COLOSSUS, 1.15f},
    {CLASS_TYPE_DRUID, CLASS_TYPE_PYRO, 0.55f},
    {CLASS_TYPE_DRUID, CLASS_TYPE_MURDEROUS, 0.80f},
    {CLASS_TYPE_DRUID, CLASS_TYPE_DEATH_K, 0.85f},
};

const int AFFINITY_COUNT = sizeof(AFFINITYRULES)/sizeof(AffinityRules);